[RFC] Add docs for the ThemeManager
ControlzEx/ControlzEx pull request #123
Opened 2020-07-09 12:29 UTC by timunie

I am not sure if I wrote everything correctly. 
1. I don't understand what is going on in the detail, so I might have missed something 
2. I am not a native English speaker, so if someone is a native speaker feel free to report spelling errors.

2020-07-10 11:04 UTC, timunie commented
Tasks to do: 
[ ] Add documentation to Theme Syncing

2020-07-14 18:35 UTC, batzen commented
@timunie just ping me if you want me to have a look. Don't want to disturb you while you are still working on it.

2020-07-14 19:11 UTC, timunie commented
Hi @batzen 

Does it look so bad? This is all I know about ThemeManager. I already got people who understood it and were able to do the Theming. 

If you can give me a feedback about what to add I would be happy to do so.

2020-07-14 19:19 UTC, batzen commented
I didn't mean to say it's bad, sorry if it sounded like that. I just wanted to offer help but didn't want to interrupt your work with review comments. Will try to add some comments in the next few days. I wrote most of the code and even i discovered new usage scenarios while using it at work. 😂

2020-07-14 20:29 UTC, timunie commented
I look forward to ylur comments or if you like it more direct changes.

2020-09-15 09:02 UTC, seba30 commented on Wiki/ThemeManager.md
> +- `Applictaion.Current`
Typo, should be **Application**

2020-09-15 09:02 UTC, seba30 commented on Wiki/ThemeManager.md
> +    - `Applictaion.Current`
Typo, should be **Application**

2020-09-15 09:02 UTC, seba30 commented on Wiki/ThemeManager.md
> +- `Applictaion.Current`
Typo, should be **Application**

2020-09-15 09:03 UTC, seba30 requested changes
Never done this before.

2020-09-15 10:47 UTC, timunie commented on Wiki/ThemeManager.md
> +    - `Applictaion.Current`
thx :pray:

2020-09-15 10:47 UTC, timunie commented on Wiki/ThemeManager.md
> +- `Applictaion.Current`
thx :pray:

2020-09-15 10:47 UTC, timunie commented on Wiki/ThemeManager.md
> +- `Applictaion.Current`
thx :pray:

2020-10-03 21:18 UTC, merged

2020-10-03 21:19 UTC, batzen commented
@timunie Thanks for contributing this!!!